#:kivy 2.3.1

<AscentListScreen>
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(20)

        MDBoxLayout:
            orientation: 'horizontal'
            adaptive_height: True
            spacing: dp(10)
            padding: dp(20), 0, 0, 0

            AreaSelector:
                id: area_selector
                adaptive_width: True
                size_hint_y: None
                pos_hint: {"center_y": 0.5}

            MDTextField:
                id: search_field
                mode: 'filled'
                on_text: root.refresh_data()
                MDTextFieldLeadingIcon:
                    icon: "magnify"
                MDTextFieldHintText:
                    text: "Search"

        MDDivider:
            size_hint_x: .9
            pos_hint: {'center_x': .5}
        MDBoxLayout:
            orientation: 'horizontal'
            adaptive_height: True
            spacing: dp(20)
            CustomMDSegmentedButton:
                type: 'medium'
                pos_hint: {'center_y': .5}
                MDSegmentedButtonItem:
                    id: sort_by_date
                    on_release: root.load_by_date()
                    active: True
                    MDSegmentButtonLabel:
                        text: 'by Date'
                MDSegmentedButtonItem:
                    id: sort_by_grade
                    on_release: root.load_by_grade()

                    MDSegmentButtonLabel:
                        text: 'by Grade'
            MDButton:
                style: 'filled'
                theme_bg_color: 'Custom'
                md_bg_color: app.theme_cls.secondaryColor
                on_release: root.manager.current = 'ascent'
                MDButtonIcon:
                    icon: 'plus'
                MDButtonText:
                    text: 'Add'

        MDRecycleView:
            viewclass: 'AscentItem'
            id: ascent_list
            scroll_type: ['bars', 'content']
            scroll_wheel_distance: dp(60)
            bar_width: dp(10)
            
            RecycleBoxLayout:
                orientation: 'vertical'
                default_size: None, dp(30)
                default_size_hint: 1, None
                size_hint_y: None
                height: self.minimum_height

<AscentItem>
    orientation: 'horizontal'
    adaptive_height: True
    spacing: dp(10)
    padding: 0, dp(5)

    canvas.after:
    # Draw a line after the content
        Color:
            rgba: 0.5, 0.5, 0.5, 1
        Line:
            points: self.x, self.y, self.right, self.y
            width: 1

    MDLabel:
        text: root.date
        adaptive_width: True
        text_color: app.theme_cls.secondaryColor
        italic: True
        pos_hint: {"center_y": .5}
        font_style: 'Body'
        role: 'medium'
    
    ClickableMDLabel:
        text: root.name
        bold: True
        font_style: 'Title' if root.is_group else 'Body'
        role: 'medium' if root.is_group else 'large'
        shorten: True
        shorten_from: 'right'
        on_release: root.show_info_dialog()
    
    MDIcon:
        icon: "lightning-bolt" if root.flash else "blank"
        icon_color_theme: 'Custom'
        icon_color: "#dbbf02"
    
    MDLabel:
        text: root.grade
        size_hint_x: None
        width: dp(35)
        halign: 'right'
        text_color: self.theme_cls.primaryColor
        font_style: 'Body'
        role: 'large'

<DialogItem>
    orientation: 'horizontal'
    adaptive_height: True
    spacing: dp(20)

    MDIcon:
        icon: root.icon
        adaptive_width: True
        pos_hint: {"center_y": 0.5}

    MDLabel:
        text: root.label
        adaptive_height: True
        allow_copy: True

<DialogScrollableItem>
    orientation: 'horizontal'
    adaptive_height: True
    spacing: dp(20)

    MDIcon:
        icon: root.icon
        adaptive_width: True
        pos_hint: {"center_y": 0.5}
        
    MDBoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        height: min(scroll_content.height, dp(300))
        MDScrollView:
            do_scroll_x: False
            bar_width: dp(10)
            MDLabel:
                id: scroll_content
                text: root.label
                adaptive_height: True
                multiline: True
                allow_copy: True