#:kivy 2.3.1

<AscentScreen>
    md_bg_color: self.theme_cls.backgroundColor
    MDBoxLayout:
        orientation: 'vertical'
        MDTopAppBar:
            type: "small"
            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "arrow-left"
                    on_release: root.manager.current = "ascent-list"
            MDTopAppBarTitle:
                text: 'Add Ascent' if not root.ascent_to_update_id else 'Update Ascent'
                text_color: app.theme_cls.primaryColor

        MDScrollView:
            do_scroll_x: False
            MDBoxLayout:
                id: ascent_form
                orientation: 'vertical'
                padding: dp(20)
                adaptive_height: True
                MDTextField:
                    id: ascent_form_name
                    mode: 'filled'
                    MDTextFieldLeadingIcon:
                        icon: "terrain"
                    MDTextFieldHintText:
                        id: text_field
                        text: "Name"
                    MDTextFieldMaxLengthText:
                        max_text_length: 64

                DropDownMenuHeader:
                    id: ascent_form_grade
                    on_release: root.open_grade_menu(self)
                    text: "Grade"
                    leading_icon: "chart-bar"
                    adaptive_size: True

                MDDivider:
                    md_bg_color: app.theme_cls.outlineVariantColor
                    divider_width: dp(1)

                DropDownMenuHeader:
                    id: ascent_form_area
                    on_release: root.open_area_menu(self)
                    text: "Area"
                    leading_icon: "map-marker"
                    adaptive_size: True

                MDDivider:
                    md_bg_color: app.theme_cls.outlineVariantColor
                    divider_width: dp(1)
                
                DropDownMenuHeader:
                    id: ascent_form_date_picker
                    on_release: root.show_date_picker()
                    text: "Date"
                    leading_icon: "calendar"
                    adaptive_size: True

                MDDivider:
                    md_bg_color: app.theme_cls.outlineVariantColor
                    divider_width: dp(1)

                MDBoxLayout:
                    orientation: 'horizontal'
                    adaptive_height: True
                    padding: 0, dp(30), 0, dp(10)
                    spacing: dp(20)

                    MDIcon:
                        icon: "lightning-bolt"
                    MDLabel:
                        text: "Flash"
                        adaptive_size: True
                    MDCheckbox:
                        id: ascent_form_flash_checkbox

                MDDivider:
                    md_bg_color: app.theme_cls.outlineVariantColor
                    divider_width: dp(1)

                MDBoxLayout:
                    adaptive_height: True
                    padding: 0, dp(30)

                    MDTextField:
                        id: ascent_form_note
                        multiline: True
                        mode: 'filled'

                        MDTextFieldLeadingIcon:
                            icon: "note"
                        MDTextFieldHelperText:
                            id: text_field
                            text: "Note (Optional)"
                            mode: 'persistent'

                MDBoxLayout:
                    orientation: "horizontal"
                    adaptive_height: True
                    spacing: dp(30)
                    Widget:
                    MDButton:
                        on_release: root.clear_all_fields()
                        MDButtonText:
                            text: 'Clear'
                    MDButton:
                        on_release: root.submit()
                        MDButtonText:
                            text: 'Add' if not root.ascent_to_update_id else 'Update'


<DropDownMenuHeader>
    orientation: "vertical"
    id: container

    MDBoxLayout:
        spacing: dp(20)
        adaptive_height: True
        adaptive_width: True
        padding: 0, dp(30), 0, dp(10)

        MDIcon:
            id: leading_icon
            icon: root.leading_icon
            size_hint: None, None
            size: "48dp", "48dp"
            theme_text_color: "Custom"
            adaptive_width: True
            text_color:
                app.theme_cls.onSurfaceVariantColor

        MDLabel:
            id: label
            text: root.text
            adaptive_size: True
            theme_text_color: "Custom"
            text_color:
                app.theme_cls.onSurfaceVariantColor
        
        MDIcon:
            id: leading_icon
            icon: "arrow-down-drop-circle"
            size_hint: None, None
            size: "48dp", "48dp"
            theme_text_color: "Custom"
            adaptive_width: True
            text_color:
                app.theme_cls.onSurfaceVariantColor

